import { Router } from 'express';
import { z } from 'zod';
import { asyncHandler } from '../../middleware/asyncHandler.js';
import { requireAuth, requirePermission } from '../../middleware/auth.js';
import { validate } from '../../middleware/validate.js';
import { ACTIONS } from '../auth/permissions.js';
import { Project } from './project.model.js';
import { Task } from './task.model.js';
import { createCompanyCrud } from '../../utils/companyCrud.js';
const objectId = z.string().regex(/^[a-f\d]{24}$/i); const base = z.object({ companyId: objectId });
const project = base.extend({ name: z.string().min(1), description: z.string().optional(), startDate: z.coerce.date().optional(), dueDate: z.coerce.date().optional(), priority: z.enum(['LOW', 'MEDIUM', 'HIGH']).default('MEDIUM') });
const task = base.extend({ projectId: objectId, title: z.string().min(1), description: z.string().optional(), assigneeId: objectId.optional(), dueDate: z.coerce.date().optional(), priority: z.enum(['LOW', 'MEDIUM', 'HIGH']).default('MEDIUM') });
const router = Router(); const projects = createCompanyCrud(Project, 'Proyecto'); const tasks = createCompanyCrud(Task, 'Tarea');
router.use(requireAuth);
router.get('/', requirePermission(ACTIONS.VIEW), validate(base, 'query'), asyncHandler(async (req, res) => res.json({ success: true, data: await projects.list(req.query), message: 'Proyectos obtenidos correctamente' })));
router.post('/', requirePermission(ACTIONS.CREATE), validate(project), asyncHandler(async (req, res) => res.status(201).json({ success: true, data: await projects.create(req.body, req.auth.userId), message: 'Proyecto creado correctamente' })));
router.get('/tasks', requirePermission(ACTIONS.VIEW), validate(base, 'query'), asyncHandler(async (req, res) => res.json({ success: true, data: await tasks.list(req.query), message: 'Tareas obtenidas correctamente' })));
router.post('/tasks', requirePermission(ACTIONS.CREATE), validate(task), asyncHandler(async (req, res) => res.status(201).json({ success: true, data: await tasks.create(req.body, req.auth.userId), message: 'Tarea creada correctamente' })));
export default router;
