import { Router } from 'express';
import { z } from 'zod';
import { asyncHandler } from '../../middleware/asyncHandler.js';
import { requireAuth, requirePermission } from '../../middleware/auth.js';
import { validate } from '../../middleware/validate.js';
import { ACTIONS } from '../auth/permissions.js';
import { Employee } from './employee.model.js';
import { Department } from './department.model.js';
import { createCompanyCrud } from '../../utils/companyCrud.js';
const objectId = z.string().regex(/^[a-f\d]{24}$/i);
const base = z.object({ companyId: objectId });
const employee = base.extend({ name: z.string().min(1), lastName: z.string().min(1), email: z.string().email().optional(), phone: z.string().optional(), position: z.string().optional(), department: z.string().optional(), hireDate: z.coerce.date().optional() });
const department = base.extend({ name: z.string().min(1), description: z.string().optional(), manager: z.string().optional() });
const router = Router(); const employees = createCompanyCrud(Employee, 'Empleado'); const departments = createCompanyCrud(Department, 'Departamento');
router.use(requireAuth);
router.get('/employees', requirePermission(ACTIONS.VIEW), validate(base, 'query'), asyncHandler(async (req, res) => res.json({ success: true, data: await employees.list(req.query), message: 'Empleados obtenidos correctamente' })));
router.post('/employees', requirePermission(ACTIONS.CREATE), validate(employee), asyncHandler(async (req, res) => res.status(201).json({ success: true, data: await employees.create(req.body, req.auth.userId), message: 'Empleado creado correctamente' })));
router.get('/departments', requirePermission(ACTIONS.VIEW), validate(base, 'query'), asyncHandler(async (req, res) => res.json({ success: true, data: await departments.list(req.query), message: 'Departamentos obtenidos correctamente' })));
router.post('/departments', requirePermission(ACTIONS.CREATE), validate(department), asyncHandler(async (req, res) => res.status(201).json({ success: true, data: await departments.create(req.body, req.auth.userId), message: 'Departamento creado correctamente' })));
export default router;
