export const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  GERENTE: 'GERENTE',
  VENTAS: 'VENTAS',
  COMPRAS: 'COMPRAS',
  ALMACEN: 'ALMACEN',
  FINANZAS: 'FINANZAS',
  RRHH: 'RRHH',
  EMPLEADO: 'EMPLEADO'
});

export const ACTIONS = Object.freeze({
  VIEW: 'VIEW',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  EXPORT: 'EXPORT',
  APPROVE: 'APPROVE'
});

const allActions = Object.values(ACTIONS);

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.ADMIN]: allActions,
  [ROLES.GERENTE]: allActions,
  [ROLES.VENTAS]: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE],
  [ROLES.COMPRAS]: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE],
  [ROLES.ALMACEN]: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE],
  [ROLES.FINANZAS]: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.APPROVE],
  [ROLES.RRHH]: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE],
  [ROLES.EMPLEADO]: [ACTIONS.VIEW]
});

export function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] ?? [];
}
