import { Router } from 'express';
import { z } from 'zod';
import { asyncHandler } from '../../middleware/asyncHandler.js';
import { requireAuth, requirePermission } from '../../middleware/auth.js';
import { validate } from '../../middleware/validate.js';
import { ACTIONS } from '../auth/permissions.js';
import { Lead } from './lead.model.js';
import { Opportunity } from './opportunity.model.js';
import { createCompanyCrud } from '../../utils/companyCrud.js';
const objectId = z.string().regex(/^[a-f\d]{24}$/i); const base = z.object({ companyId: objectId });
const lead = base.extend({ name: z.string().min(1), email: z.string().email().optional(), phone: z.string().optional(), source: z.string().optional(), notes: z.string().optional() });
const opportunity = base.extend({ name: z.string().min(1), leadId: objectId.optional(), amount: z.coerce.number().nonnegative().default(0), expectedCloseDate: z.coerce.date().optional() });
const router = Router(); const leads = createCompanyCrud(Lead, 'Lead'); const opportunities = createCompanyCrud(Opportunity, 'Oportunidad');
router.use(requireAuth);
router.get('/leads', requirePermission(ACTIONS.VIEW), validate(base, 'query'), asyncHandler(async (req, res) => res.json({ success: true, data: await leads.list(req.query), message: 'Leads obtenidos correctamente' })));
router.post('/leads', requirePermission(ACTIONS.CREATE), validate(lead), asyncHandler(async (req, res) => res.status(201).json({ success: true, data: await leads.create(req.body, req.auth.userId), message: 'Lead creado correctamente' })));
router.get('/opportunities', requirePermission(ACTIONS.VIEW), validate(base, 'query'), asyncHandler(async (req, res) => res.json({ success: true, data: await opportunities.list(req.query), message: 'Oportunidades obtenidas correctamente' })));
router.post('/opportunities', requirePermission(ACTIONS.CREATE), validate(opportunity), asyncHandler(async (req, res) => res.status(201).json({ success: true, data: await opportunities.create(req.body, req.auth.userId), message: 'Oportunidad creada correctamente' })));
export default router;
